language: php 

os:
    - linux

php:
    - 7.0
    - 7.1
    - 7.2

compiler:
      - gcc

notifications:
    email: false

env:
    - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
    - ./travis/compile.sh

script:
    - ./travis/run-test.sh
